### ISSUE TITLE
Unable to pull data from group containing content relationships

### ISSUE THREAD

**Issue by stoutlabs** [angeloashmore/gatsby-source-prismic#43]
I have a content type of 'Location', which holds a group of content relationships to a content type of 'Project'. (E.g. the "New York" location holds around 10 "Projects".) 

1. I have no problem fetching the correct data via GraphiQL... but it errors out when compiling with the same query.

2. I have no trouble pulling the data when the content relationship is 1:1... things compile fine.

This is my query in gatsby-node.js.

```javascript
const projectsByLocation = await graphql(`
      {
         allPrismicLocations {
            edges {
               node {
                  uid
                  data {
                     projects {
                        project {
                           document {
                              uid
                           }
                        }
                     }
                     title {
                        text
                     }
                  }
               }
            }
         }
      }
   `);
````
(This works perfectly in GraphiQL... but fails on compile with an error message of:  "TypeError: Cannot read property 'allPrismicLocations' of undefined.)

And removing 
````javascript
projects {
   project {
      document { 
         uid
      }
   }
}
````
allows it to compile fine, but with no project data.

Is this a limitation, or am I doing something incorrectly? Sorry - my brain is mush after trying to solve this for the past 7 hours.

**Comment by stoutlabs** [comment]
Update:
After some sleep (ha!), and a little digging in the docs /debugging... I was led to try this:

````javascript
projects {
  theproject {
    __typename
    ... on theproject {
      document {
         id
         uid
      }
    }
  }
}
````
Which finally pulled all the necessary related data into Gatsby! 😃 

(I'm still not sure why the original query works in GraphiQL though.)

**Comment by angeloashmore** [comment]
Hey @stoutlabs, glad you were able to find some kind of workaround. That looks unusual, so I hope we can find why it works and why the first query doesn't.

Based on that updated query, it looks like `theproject` could contain multiple types of nodes.

Are you able to view the different `__typename` values? Maybe there's another field elsewhere in your data that uses the same name that's causing the unexpected behavior?

**Comment by stoutlabs** [comment]
Hey! In Prismic, I have that group field (api ID is 'theprojects') limited to only contain items of content type "project". I console logged the query output, and the typename values present are all "theproject".

Note: I had renamed the group field's api ID to "theprojects" from "projects", and the repeating relational field's api ID to "theproject" from "project", just in case there was a naming conflict. That had no effect... it worked in graphiQL, but not Gatsby. (It only worked in Gatsby after I changed it to the ````... on project { }```` syntax mentioned above.)

**Comment by angeloashmore** [comment]
If you're able to, could you post your Prismic JSON schema for your Locations custom type?

**Comment by angeloashmore** [comment]
I'm going to rubber duck a bit here.

If the Link field (`theproject` in this case) could contain multiple types, then `__typename` becomes available and `... on PrismicMyContentType {}` becomes necessary.

For example, if you have a Group called `my_relations`, containing a Link field called `relation` which links to a `Page` and `Image` custom type, then you could use the following to query it:

```graphql
{
  allPrismicMyContentType {
    edges {
      node {
        data {
          my_relations {
            relation {
              document {
                __typename
                ... on PrismicPage {
                  uid
                }
                ... on PrismicImage {
                  uid
                }
              }
            }
          }
        }
      }
    }
  }
}
```

If the `relation` Link field only contains a single type of content, then `__typename` and `... on PrismicMyContentType {}` is not necessary (and will probably error).

```graphql
{
  allPrismicMyContentType {
    edges {
      node {
        data {
          my_relations {
            relation {
              document {
                uid
              }
            }
          }
        }
      }
    }
  }
}
```

So based on this, your original query looks right.

The only way `__typename` could be available under `theproject` is if

**Comment by stoutlabs** [comment]
Maybe it's due to the repeating field being a custom type? I see in the JSON schema where Prismic puts it into an array ("customtypes"), and with non-custom repeating fields it uses a single "type" field.

(In other words, perhaps since the "type" is wrapped in an array it assumes the possibility of multiple types... even if there is only one currently in use.)

**Comment by stoutlabs** [comment]
Hmm... the type that is returned for "theproject" is "theproject_2".

**Comment by henrymyers** [comment]
I'm having a very similar issue.

I have a group containing only content relationships (restricted to a single type), but in GraphiQL and Gatsby, each item is missing the `document` property. As was the case for @stoutlabs, 1:1 content relationships work fine.

Knowing that `plans` is a group of *pricing_plan* and `recommended_plan` is a single *pricing_plan* :

Here is the query in GraphiQL
<img width="479" alt="graphiql" src="https://user-images.githubusercontent.com/942003/45182104-6040ea80-b1ee-11e8-96fa-c3a33d3941d5.png">

The fields in Prismic
![prismic_tab](https://user-images.githubusercontent.com/942003/45182121-6df67000-b1ee-11e8-9768-0379cea01628.png)

The PricingTab fields in our *redux-state.json*
![redux_state_](https://user-images.githubusercontent.com/942003/45182330-e8bf8b00-b1ee-11e8-92e7-151034f57f94.png)

And one PricingPlan from our same *redux-state.json*
![screen shot 2018-09-06 at 4 05 50 pm](https://user-images.githubusercontent.com/942003/45182373-02f96900-b1ef-11e8-8dfa-5f20bf13ff3d.png)

Any ideas are welcome, as this is pretty much a blocking issue for us.

Thanks!

**Comment by henrymyers** [comment]
After further investigation, this is due to a Gatsby issue.

See PR https://github.com/gatsbyjs/gatsby/pull/7971

**Comment by henrymyers** [comment]
Fix merged in gatsby@2.0.0-rc.19

**Comment by angeloashmore** [comment]
@henrymyers Thanks for pointing that out! Everything looked right on our end, so that was confusing.

**Comment by angeloashmore** [comment]
Closing this as it seems to have been resolved.

**Comment by jordyvanraaij** [comment]
I'm using the V3 version and I'm running into the same issue. I can't get the content from a Group of documents. Anyone else experiencing this?

**Comment by jordyvanraaij** [comment]
@angeloashmore I know the queries are different, but I thought you still need the document before you can do the `... on Blah` query? In the following screenshot I'd expect the option to spread the content type PrismicCase but it can't find it. The `document` is also not available on `case` and if I use the suggested `PrismicCasesOverviewDataCasesCase` I still can't get the data. Do you have a solution or can you reproduce this?

<img width="775" alt="Screenshot 2019-09-16 at 09 33 06" src="https://user-images.githubusercontent.com/5711197/64940713-07764a00-d865-11e9-9708-35f6e35e6fee.png">

**Comment by jordyvanraaij** [comment]
> @angeloashmore I know the queries are different, but I thought you still need the document before you can do the `... on Blah` query? In the following screenshot I'd expect the option to spread the content type PrismicCase but it can't find it. The `document` is also not available on `case` and if I use the suggested `PrismicCasesOverviewDataCasesCase` I still can't get the data. Do you have a solution or can you reproduce this?
> 
> <img alt="Screenshot 2019-09-16 at 09 37 11" width="776" src="https://user-images.githubusercontent.com/5711197/64940929-95523500-d865-11e9-8472-cfbdf34445fa.png">

@angeloashmore Do you have any idea? We're kind of stuck now and can't rollout the preview functionality for our website. If you need anything from me for you to test please let me know.

**Comment by henrymyers** [comment]
@jordyvanraaij if `case` is a link field pointing to another document, you should have a `document` property inside the link field.
```
prismicCasesOverview {
    data {
        cases {
            case {
                document {
                    uid
                    data {
                        meta_title
                    }
                }
            }
        }
    }
}
```

**Comment by Hahlh** [comment]
@jordyvanraaij (or maybe @angeloashmore) 
Did you find a fix for this at some point or realized where you went wrong?

I am currently facing the exact same issue. 

After having created a single type for a page, I added two content relationship for selecting two featured articles, but I am unable to see "document" as a query option.

![image](https://user-images.githubusercontent.com/45669613/103488141-99171b80-4e0a-11eb-8702-9a279770767f.png)

![image](https://user-images.githubusercontent.com/45669613/103487985-79332800-4e09-11eb-98df-9abe987cfdb6.png)
 
I double checked the schemas several times, experimented with using selection fields instead and tried to use prismicHome, but all to no avail.

I also can't access "document" if I look at dataRaw instead.

What am I missing? 

I would be thankful if someone could point me in the right direction.

**Comment by angeloashmore** [comment]
@Hahlh Can you double check that you added your `page` custom type JSON schema to `gatsby-config.js`?

It looks like Gatsby is inferring the types, so it doesn't know that "PrismicPage" is a Prismic document.

You should be providing it to the `schemas` option like the following:

```js
{
  resolve: 'gatsby-source-prismic',
  options: {
    // your other options
    schemas: {
      // your other schemas
      page: require('./src/schemas/page.json'), // Replace the path to the JSON file in your project
    }
  }
}
```

**Comment by Hahlh** [comment]
@angeloashmore , you are great!

This is the second time, not adding the schema to gatsby-config.js was the cause of an issue.

Thank you for your fast response and your help!

**Comment by angeloashmore** [comment]
@Hahlh Great, glad to hear it's working!

The next major version of the plugin will tell you if you're missing a schema to help others in the future. Something like the following will be printed when running `gatsby develop`:

```
 ERROR #11331  PLUGIN

Invalid plugin options for "gatsby-source-prismic":

- JSON schema for "navigation" is missing
- JSON schema for "not_found_page" is missing
- JSON schema for "settings" is missing

not finished load plugins - 0.720s
```

**Comment by Hahlh** [comment]
That would be a great addition. Thank you again for the help!
